Resolve #99: Fix abigen with int expression template arguments
AntelopeIO/cdt pull request #100
Opened 2023-01-27 05:08 UTC by nathanielhourt

## Change Description
Resolve #99
In my contracts, I use several template arguments which are expressions which resolve to integral values (such as an `eosio::name`) but are not literal integer values. This works great in my contracts, but causes abigen to fail.

This PReq fixes abigen in such cases where a template argument is an expression that resolves to an integer, but isn't an integer literal.

## API Changes
- [ ] API Changes

## Documentation Additions
- [ ] Documentation Additions

2023-01-27 05:09 UTC, nathanielhourt commented
Historical note: This PReq is identical to [eosio.cdt#1250](https://github.com/EOSIO/eosio.cdt/pull/1250).

2023-03-17 18:17 UTC, ScottBailey commented on tools/include/eosio/gen.hpp
> +             return ce->getResultAsAPSInt().toString(10);
Feels like some extra brackets would improve readability and match the style of the code block around it.

```suggestion
         } else if (auto ce = llvm::dyn_cast<clang::ConstantExpr>(std::get<clang::Expr*>(arg))) {
             return ce->getResultAsAPSInt().toString(10);
         }
```

2023-03-17 22:22 UTC, dimas1185 requested changes
looks good. please add a test to `tests/abigen-pass` directory. look at other examples, there are small *.json, *.abi and *.cpp to demonstrate how this works

2023-03-19 03:42 UTC, nathanielhourt commented
Good call. Added a test which fails before the fix, and passes after.

2023-03-20 14:10 UTC, dimas1185 approved these changes

2023-03-20 14:27 UTC, ScottBailey approved these changes

2023-03-20 14:27 UTC, merged