Fix some issues when building EOSIO contracts
AntelopeIO/cdt pull request #115
Opened 2023-03-15 03:30 UTC by spoonincode

This is a backport of EOSIO/eosio.cdt#968 / EOSIO/eosio.cdt#1070 that resolves EOSIO/eosio.cdt#742. 

> * Fix dependency file generation (-MD/-MMD) to hold the original source and not the generated temporary file.
> * Make temporary filenames unique to avoid races in parallel builds.

2023-03-17 01:43 UTC, larryk85 requested changes

2023-03-17 01:43 UTC, larryk85 commented on tools/cc/cdt-cpp.cpp.in
> +               llvm::sys::fs::createTemporaryFile("eosio", ".o", res);
I would like to see that as something other than 'eosio' too.  But, it's not the end of the world as it is a consumed temporary.

2023-04-04 23:17 UTC, larryk85 approved these changes

2023-04-05 01:46 UTC, heifner approved these changes

2023-04-05 02:27 UTC, merged