cdt-ld man page created
AntelopeIO/cdt pull request #144
Opened 2023-04-14 14:33 UTC by jolly-fellow

## A man page for cdt-ld utility was created for issue #121 

## API Changes
- [ ] API Changes

## Documentation Additions
- [x ] Documentation Additions

2023-04-14 19:48 UTC, ScottBailey commented on docs/man/cdt-ld.1.md
> +header: User Manual
This is probably better:
```suggestion
header: Contract Development Toolkit (CDT)
```

2023-04-14 19:49 UTC, ScottBailey requested changes
Please consider improving header.

2023-04-17 10:52 UTC, jolly-fellow commented on docs/man/cdt-ld.1.md
> +header: User Manual
> Contract Development Toolkit (CDT)

Updated

2023-04-17 16:47 UTC, ScottBailey approved these changes

2023-04-18 12:06 UTC, merged