add explicit overloads
AntelopeIO/cdt pull request #191
Opened 2023-06-07 21:09 UTC by larryk85

## Change Description

Add additional explicit stream operator overloads for `basic_string<uint8_t>` as there is a bug that fails to match against `basic_string<T>`.

Resolves #190

## API Changes
- [ ] API Changes

## Documentation Additions
- [ ] Documentation Additions

2023-06-08 12:29 UTC, heifner approved these changes

2023-06-08 13:37 UTC, ScottBailey commented on libraries/eosiolib/core/eosio/datastream.hpp
> + *  @tparam T - Type of the object contained in the basic_string
I don't see a `T` - copy paste error? 
```suggestion
```

2023-06-08 13:37 UTC, ScottBailey commented on libraries/eosiolib/core/eosio/datastream.hpp
> + *  @tparam T - Type of the object contained in the basic_string
I don't see a `T` - copy paste error? 
```suggestion
```

2023-06-08 13:39 UTC, ScottBailey requested changes
Docs are slightly out of sync with code.

2023-06-29 03:18 UTC, dimas1185 approved these changes

2023-06-29 03:18 UTC, merged