remove ubuntu18 from builds
AntelopeIO/cdt pull request #214
Opened 2023-08-22 22:57 UTC by ericpassmore

## Summary
Removed ubuntu18 from builds, as we no longer support this version for CDT. Removing unbuntu18 allows us to proceed with additional upgrades and support later versions of c++, llvm, and clang/gcc.

## Changes
in `build.yaml` removed `unbuntu18` from list of builds and removed `unbuntu18` specific compatibility steps.

Resolves #213

2023-08-22 23:21 UTC, spoonincode requested changes
also remove
https://github.com/AntelopeIO/cdt/blob/0056647020ebcd104c958ac306faff6011156670/.cicd/platforms.json#L1-L4
and the file it is pointing to

2023-08-23 21:26 UTC, spoonincode commented
also remove the `.cicd/platforms/ubuntu18.Dockerfile` file

2023-08-23 22:24 UTC, ericpassmore commented on .github/workflows/build.yaml
> -        - name: Package (Ubuntu 18 only)
Artifact is back  you can see from image below
<img width="1007" alt="Screenshot 2023-08-23 at 3 23 28 PM" src="https://github.com/AntelopeIO/cdt/assets/6685407/736f0fb0-e728-49a6-af0e-804cf1208cdf">

2023-08-24 00:04 UTC, spoonincode approved these changes

2023-08-24 14:19 UTC, dimas1185 approved these changes

2023-08-24 14:31 UTC, merged