Implemented interface for bls_signatures
AntelopeIO/cdt pull request #92
Opened 2023-01-21 16:29 UTC by systemzax

## Change Description

This pull request introduces aggregate signatures (BLS signature scheme) as a protocol feature. It uses Chia's BLS-signatures library, which in turn depends on the Relic toolkit.

## API Changes

It defines the following new host functions : 

bls_verify
bls_aggregate_pubkeys
bls_aggregate_sigs
bls_aggregate_verify

as well as new built-in types :

bls_public_key
bls_signature

Unit tests are included in libraries/libfc/test/test_bls.cpp

## Documentation Additions

Documentation of the new features will be provided on demand

2023-06-29 03:49 UTC, dimas1185 commented on libraries/eosiolib/core/eosio/crypto_bls_ext.hpp
> +   bool bls_verify(bls_public_key pub, bls_signature sig , std::vector<uint8_t> msg) {
pass by reference or explain why do you pass parameters by value here. same for other wrappers

2023-06-29 03:50 UTC, dimas1185 commented on libraries/eosiolib/core/eosio/crypto_bls_ext.hpp
> +/*   bool bls_verify( const char* sig, uint32_t sig_len, const char* dig, uint32_t dig_len, char* pub, uint32_t pub_len) {
remove unnecessary comment

2023-06-29 03:51 UTC, dimas1185 requested changes
please add integration tests. see comment for similar PR: https://github.com/AntelopeIO/cdt/pull/154#pullrequestreview-1504500825

2023-09-01 23:56 UTC, arhag commented
This was an old approach that we will no longer be going with. Instead we will use the existing BLS host functions merged into the `main` branch of Leap to implement verification in contract as needed.

2023-09-01 23:56 UTC, closed without merging